# Generated by Django 4.2.4 on 2023-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
