# Generated by Django 4.2.4 on 2023-08-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_album', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Melody Hub Album',
        ),
    ]
