# Generated by Django 4.2.4 on 2023-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_album', '0003_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
