# Generated by Django 4.2.4 on 2024-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_album", "0004_alter_album_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSamplFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=1000)),
                (
                    "sample_file",
                    models.FileField(upload_to="email_processor/sample_test_files"),
                ),
                ("sample_file_header_row", models.IntegerField()),
                ("delete_file", models.BooleanField(default=True)),
            ],
        ),
    ]
