# Generated by Django 4.2.4 on 2024-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_album", "0005_uploadsamplfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadsamplfile",
            old_name="customer_name",
            new_name="file_name",
        ),
        migrations.RemoveField(
            model_name="uploadsamplfile",
            name="delete_file",
        ),
        migrations.RemoveField(
            model_name="uploadsamplfile",
            name="sample_file_header_row",
        ),
        migrations.AlterField(
            model_name="uploadsamplfile",
            name="sample_file",
            field=models.FileField(upload_to="sample_files/"),
        ),
    ]
